apiVersion: v1
description: Spot Termination exporter Helm chart for Kubernetes
home: https://banzaicloud.com
keywords:
- spot
- aws
- lifecycle
- hollowtrees
maintainers:
- email: info@banzaicloud.com
  name: Banzai Cloud
name: spot-termination-exporter
sources:
- https://github.com/banzaicloud/banzai-charts
version: 0.0.8
